# Definition of all artefacts available in the system

ARTEFACT_NO_ARTEFACT = "artefact-no-artefact"
ARTEFACT_GOLANG_PROJECT_INFO_FEDORA = "golang-project-info-fedora"
ARTEFACT_GOLANG_PROJECT_TO_PACKAGE_NAME = "golang-project-to-package-name"
ARTEFACT_GOLANG_IPPREFIX_TO_PACKAGE_NAME = "golang-ipprefix-to-package-name"
ARTEFACT_GOLANG_PROJECT_PACKAGES = "golang-project-packages"
ARTEFACT_GOLANG_PROJECT_EXPORTED_API = "golang-project-exported-api"
ARTEFACT_GOLANG_PROJECTS_API_DIFF = "golang-projects-api-diff"
ARTEFACT_GOLANG_PROJECT_DISTRIBUTION_PACKAGES = "golang-project-distribution-packages"
ARTEFACT_GOLANG_PROJECT_DISTRIBUTION_EXPORTED_API = "golang-project-distribution-exported-api"
ARTEFACT_GOLANG_PROJECT_CONTENT_METADATA = "golang-project-content-metadata"
ARTEFACT_GOLANG_PROJECT_DISTRIBUTION_BUILD = "golang-project-distribution-build"
ARTEFACT_GOLANG_PROJECT_DISTRIBUTION_PACKAGE_BUILDS = "golang-project-distribution-package-builds"
ARTEFACT_GOLANG_PROJECT_REPOSITORY_COMMIT = "golang-project-repository-commit"
ARTEFACT_GOLANG_PROJECT_REPOSITORY_INFO = "golang-project-repository-info"
ARTEFACT_CACHE_GOLANG_PROJECT_REPOSITORY_COMMITS = "cache-golang-project-repository-commits"
ARTEFACT_GOLANG_IPPREFIX_TO_RPM="golang-ipprefix-to-rpm"
ARTEFACT_GOLANG_DISTRIBUTION_SNAPSHOT="golang-distribution-snapshot"
ARTEFACT_CACHE_GOLANG_PROJECT_DISTRIBUTION_PACKAGE_BUILDS = "cache-golang-project-distribution-package-builds"

ARTEFACT_GOLANG_PROJECT_API = "golang-project-api"
ARTEFACT_GOLANG_PROJECT_CONTRACTS = "golang-project-contracts"
ARTEFACT_GOLANG_PROJECT_STATIC_ALLOCATIONS = "golang-project-static-allocations"

ARTEFACT_GOLANG_PROJECT_DISTRIBUTION_API = "golang-project-distribution-api"
ARTEFACT_GOLANG_PROJECT_DISTRIBUTION_CONTRACTS = "golang-project-distribution-contracts"
ARTEFACT_GOLANG_PROJECT_DISTRIBUTION_STATIC_ALLOCATIONS = "golang-project-distribution-static-allocations"
